[workspace]
members = [
	"cli",
	"gui", "engine",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Wannes Malfait"]
description = "A solver for the board game: Second Best!"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
