[package]
name = "engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "search_speed"
harness = false
