[package]
name = "second-best-gui"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "A gui to play and analyze the board game: Second Best!"

[dependencies]
bevy_egui  = "0.28"
bevy = "0.14"
engine = { path = "../engine" }
